/comm/param/ctrl/is_ready_to_capture: true
/comm/param/ctrl/is_ready_to_serve: true
/voice/param/is_ready_to_interrupt: false
/voice/param/is_ready_to_play: false
/voice/param/is_ready_to_remind: false
/voice/param/is_ready_to_translate: false
